#!/bin/bash

sudo wget -o /usr/share/tetris/sounds/bgm.wav http://projects.catz.gq/linux%20Projects/tetris-extra/Astral.wav;
sudo wget -o /usr/share/tetris/sounds/Ronin.wav http://projects.catz.gq/linux%20Projects/tetris-extra/Onyx%20-%20Sunlight.wav;
